
'use strict';

// app-cfg
export const ACTIVITI = {
  CONFIG:{
    'contextRoot' : '/service',
  }
}

export const EVENTS_SELECT_OPTION = [
  { title: null, label: 'ACTIVITY_CANCELLED'},
  { title: 'EVENT_TYPE.ACTIVITY.COMPENSATE.TOOLTIP', label: 'ACTIVITY_COMPENSATE'},
  { title: 'EVENT_TYPE.ACTIVITY.COMPLETED.TOOLTIP', label: 'ACTIVITY_COMPLETED'},
  { title: 'bla', label: 'ACTIVITY_ERROR_RECEIVED'},
  { title: null, label: 'ACTIVITY_MESSAGE_CANCELLED'},
  { title: null, label: 'ACTIVITY_MESSAGE_RECEIVED'},
  { title: null, label: 'ACTIVITY_MESSAGE_WAITING'},
  { title: null, label: 'ACTIVITY_SIGNALED'},
  { title: null, label: 'ACTIVITY_SIGNAL_WAITING'},
  { title: null, label: 'ACTIVITY_STARTED'},
  { title: null, label: 'CUSTOM'},
  { title: null, label: 'ENGINE_CLOSED'},
  { title: null, label: 'ENGINE_CREATED'},
  { title: null, label: 'ENTITY_ACTIVATED'},
  { title: null, label: 'ENTITY_CREATED'},
  { title: null, label: 'ENTITY_DELETED'},
  { title: null, label: 'ENTITY_INITIALIZED'},
  { title: null, label: 'ENTITY_SUSPENDED'},
  { title: null, label: 'ENTITY_UPDATED'},
  { title: null, label: 'HISTORIC_ACTIVITY_INSTANCE_CREATED'},
  { title: null, label: 'HISTORIC_ACTIVITY_INSTANCE_ENDED'},
  { title: null, label: 'HISTORIC_PROCESS_INSTANCE_CREATED'},
  { title: null, label: 'HISTORIC_PROCESS_INSTANCE_ENDED'},
  { title: null, label: 'JOB_CANCELED'},
  { title: null, label: 'JOB_EXECUTION_FAILURE'},
  { title: null, label: 'JOB_EXECUTION_SUCCESS'},
  { title: null, label: 'JOB_RESCHEDULED'},
  { title: null, label: 'JOB_RETRIES_DECREMENTED'},
  { title: 'EVENT_TYPE.MEMBERSHIP.CREATED.TOOLTIP', label: 'MEMBERSHIP_CREATED'},
  { title: 'EVENT_TYPE.MEMBERSHIP.DELETED.TOOLTIP', label: 'MEMBERSHIP_DELETED'},
  { title: 'EVENT_TYPE.MEMBERSHIPS.DELETED.TOOLTIP', label: 'MEMBERSHIPS_DELETED'},
  { title: null, label: 'MULTI_INSTANCE_ACTIVITY_CANCELLED'},
  { title: null, label: 'MULTI_INSTANCE_ACTIVITY_COMPLETED'},
  { title: null, label: 'MULTI_INSTANCE_ACTIVITY_COMPLETED_WITH_CONDITION'},
  { title: null, label: 'MULTI_INSTANCE_ACTIVITY_STARTED'},
  { title: null, label: 'PROCESS_CANCELLED'},
  { title: null, label: 'PROCESS_COMPLETED'},
  { title: null, label: 'PROCESS_COMPLETED_WITH_TERMINATE_END_EVENT'},
  { title: null, label: 'PROCESS_COMPLETED_WITH_ERROR_END_EVENT'},
  { title: null, label: 'PROCESS_CREATED'},
  { title: null, label: 'PROCESS_STARTED'},
  { title: null, label: 'SEQUENCEFLOW_TAKEN'},
  { title: 'EVENT_TYPE.TASK.ASSIGNED.TOOLTIP', label: 'TASK_ASSIGNED'},
  { title: 'EVENT_TYPE.TASK.COMPLETED.TOOLTIP', label: 'TASK_COMPLETED'},
  { title: null, label: 'TASK_CREATED'},
  { title: null, label: 'TIMER_FIRED'},
  { title: null, label: 'TIMER_SCHEDULED'},
  { title: 'EVENT_TYPE.UNCAUGHT.BPMNERROR.TOOLTIP', label: 'UNCAUGHT_BPMN_ERROR'},
  { title: 'EVENT_TYPE.VARIABLE.CREATED.TOOLTIP', label: 'VARIABLE_CREATED'},
  { title: 'EVENT_TYPE.VARIABLE.DELETED.TOOLTIP', label: 'VARIABLE_DELETED'},
  { title: 'EVENT_TYPE.VARIABLE.UPDATED.TOOLTIP', label: 'VARIABLE_UPDATED'},
]